Repository SchwarzIT/onyx, pull requests merged in 2024-03, with the labels that each got.

#449 chore: update to Storybook 8 rc
  packages/sit-onyx/package.json
  packages/storybook-utils/package.json
  pnpm-lock.yaml
Labels: dependencies

#462 docs(home): update component roadmap
  apps/docs/src/.vitepress/components/ComponentCard.stories.ts
  apps/docs/src/.vitepress/components/ComponentCard.vue
  apps/docs/src/.vitepress/components/ComponentGrid.vue
  apps/docs/src/.vitepress/components/ComponentRoadmap.stories.ts
  apps/docs/src/.vitepress/components/ComponentRoadmap.vue
  apps/docs/src/.vitepress/components/ComponentStatusBadge.stories.ts
  apps/docs/src/.vitepress/components/ComponentStatusBadge.vue
  apps/docs/src/.vitepress/components/OnyxHomePage.stories.ts
  apps/docs/src/.vitepress/components/OnyxHomePage.vue
  apps/docs/src/.vitepress/components/TabGroup.vue
  apps/docs/src/index.data.ts
  apps/docs/src/index.md
  apps/docs/tsconfig.json
  apps/docs/vite.config.ts
  packages/sit-onyx/src/components/OnyxButton/OnyxButton.vue
Labels: documentation

#500 chore: update Storybook
  package.json
  pnpm-lock.yaml
Labels: dependencies

#534 chore: update Storybook to 8.0.0-rc.3
  package.json
  pnpm-lock.yaml
Labels: dependencies

#631 fix: prevent playwright heap memory issue
  packages/chartjs-plugin/playwright/snapshots/stories/DoughnutChart/doughnut-dark-chromium-linux.png
  packages/sit-onyx/playwright.config.ts
  packages/sit-onyx/playwright/snapshots/components/OnyxButton/button-state--default-variation--secondary-mode--default-focusState--focus-visible-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxSwitch/switch-state--required-select--unselected-focusState--hover-labeled--labeled-chromium-linux.png
  packages/sit-onyx/src/components/OnyxButton/OnyxButton.ct.tsx
  packages/sit-onyx/src/components/OnyxCheckbox/OnyxCheckbox.ct.tsx
  packages/sit-onyx/src/components/OnyxIconButton/OnyxIconButton.ct.tsx
  packages/sit-onyx/src/components/OnyxInput/OnyxInput.ct.tsx
  packages/sit-onyx/src/components/OnyxLink/OnyxLink.ct.tsx
  packages/sit-onyx/src/components/OnyxRadioButton/OnyxRadioButton.ct.tsx
  packages/sit-onyx/src/components/OnyxSwitch/OnyxSwitch.ct.tsx
  packages/sit-onyx/src/utils/playwright.tsx
Labels: bug

#774 docs: fix wrong spelling in onyx website
  apps/docs/src/basics/index.md
Labels: bug, documentation

#773 fix: update color value for light/dark mode in `getDatasetColors()`
  .changeset/cold-pigs-march.md
  packages/chartjs-plugin/src/utils.ts
Labels: bug

#775 fix(OnyxTooltip): add missing type for open property
  .changeset/forty-months-carry.md
  packages/sit-onyx/src/components/OnyxSwitch/OnyxSwitch.stories.ts
  packages/sit-onyx/src/components/OnyxTooltip/types.ts
  packages/sit-onyx/tsconfig.app.json
Labels: bug
