Repository SchwarzIT/onyx, pull requests merged in 2024-02, with the labels that each got.

#206 feat: add component `OnyxHeadline`
  .changeset/modern-comics-occur.md
  apps/docs/src/.vitepress/components/ComponentCard.vue
  apps/docs/src/basics/typography.md
  apps/docs/src/index.data.ts
  packages/sit-onyx/playwright/snapshots/components/OnyxHeadline/default-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxHeadline/default-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxHeadline/default-webkit-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxHeadline/monospace-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxHeadline/monospace-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxHeadline/monospace-webkit-linux.png
  packages/sit-onyx/src/components/OnyxHeadline/OnyxHeadline.ct.tsx
  packages/sit-onyx/src/components/OnyxHeadline/OnyxHeadline.stories.ts
  packages/sit-onyx/src/components/OnyxHeadline/OnyxHeadline.vue
  packages/sit-onyx/src/components/OnyxHeadline/types.ts
  packages/sit-onyx/src/index.ts
Labels: enhancement

#218 docs: integrate changelogs
  apps/docs/src/.vitepress/config.ts
  apps/docs/src/.vitepress/utils.ts
  apps/docs/src/development/packages/changelogs/[name].md
  apps/docs/src/development/packages/changelogs/[name].paths.ts
  apps/docs/src/development/packages/figma-utils.md
  apps/docs/src/development/packages/headless.md
  apps/docs/src/development/packages/storybook-utils.md
  apps/docs/src/development/packages/vitepress-theme.md
  apps/docs/src/index.data.ts
Labels: documentation

#234 docs: set Storybook dark mode correctly when switching VitePress theme
  packages/storybook-utils/src/preview.ts
Labels: bug, documentation

#216 docs: define component states
  apps/docs/src/.vitepress/config.ts
  apps/docs/src/basics/states.md
Labels: documentation

#236 docs: use OnyxHeadline for typography preview
  apps/docs/src/.vitepress/components/OnyxTypography.vue
  apps/docs/src/basics/typography.md
  apps/docs/tsconfig.json
Labels: documentation

#247 docs: rename Jannick to "Keller" 🤵🏽‍♂️
  apps/docs/src/brand/team.md
Labels: documentation

#241 docs: add foundations topic cards and iconography page
  apps/docs/src/assets/accessibility-thumbnail.png
  apps/docs/src/assets/colors-thumbnail.png
  apps/docs/src/assets/density-thumbnail.png
  apps/docs/src/assets/elevation-thumbnail.png
  apps/docs/src/assets/grid-thumbnail.png
  apps/docs/src/assets/iconography-thumbnail.png
  apps/docs/src/assets/icons-angles.png
  apps/docs/src/assets/icons-corners.png
  apps/docs/src/assets/icons-grid.png
  apps/docs/src/assets/icons-layout-1.png
  apps/docs/src/assets/icons-layout-2.png
  apps/docs/src/assets/icons-layout-3.png
  apps/docs/src/assets/icons-overview.png
  apps/docs/src/assets/icons-stroke-1.png
  apps/docs/src/assets/icons-stroke-2.png
  apps/docs/src/assets/images-thumbnail.png
  apps/docs/src/assets/infographics-thumbnail.png
  apps/docs/src/assets/layout-thumbnail.png
  apps/docs/src/assets/motion-thumbnail.png
  apps/docs/src/assets/states-thumbnail.png
  apps/docs/src/assets/truncation-thumbnail.png
  apps/docs/src/assets/typography-thumbnail.png
  apps/docs/src/assets/units-thumbnail.png
  apps/docs/src/basics/accessibility.md
  apps/docs/src/basics/colors.md
  apps/docs/src/basics/iconography.md
  apps/docs/src/basics/images.md
  apps/docs/src/basics/index.md
  apps/docs/src/basics/layout.md
  apps/docs/src/basics/truncation.md
  apps/docs/src/basics/typography.md
  apps/docs/src/tokens/introduction.md
Labels: documentation

#270 fix(OnyxIcon): remove default browser margin
  .changeset/sharp-ravens-stare.md
  packages/sit-onyx/playwright/snapshots/components/OnyxIcon/colors-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxIcon/colors-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxIcon/colors-webkit-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxIcon/default-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxIcon/default-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxIcon/default-webkit-linux.png
  packages/sit-onyx/src/components/OnyxHeadline/OnyxHeadline.vue
  packages/sit-onyx/src/components/OnyxIcon/OnyxIcon.ct.tsx
  packages/sit-onyx/src/components/OnyxIcon/OnyxIcon.vue
Labels: bug

#281 docs: fix Storybook table overflow
  packages/sit-onyx/.storybook/docs-template.scss
Labels: bug, documentation

#298 feat(OnyxCheckbox): add property `disabled`
  .changeset/smooth-onions-clap.md
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/checked-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/checked-default-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/checked-default-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/checked-default-webkit-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/checked-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/checked-focus-visible-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/checked-focus-visible-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/checked-focus-visible-webkit-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/checked-hover-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/checked-hover-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/checked-hover-webkit-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/checked-webkit-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/default-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/default-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/default-webkit-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/disabled-checked-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/disabled-checked-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/disabled-checked-webkit-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/disabled-indeterminate-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/disabled-indeterminate-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/disabled-indeterminate-webkit-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/disabled-unchecked-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/disabled-unchecked-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/disabled-unchecked-webkit-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/focus-visible-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/focus-visible-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/focus-visible-webkit-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/hover-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/hover-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/hover-webkit-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/indeterminate-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/indeterminate-default-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/indeterminate-default-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/indeterminate-default-webkit-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/indeterminate-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/indeterminate-focus-visible-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/indeterminate-focus-visible-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/indeterminate-focus-visible-webkit-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/indeterminate-hover-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/indeterminate-hover-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/indeterminate-hover-webkit-linux.png
  packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/indeterminate-webkit-linux.png
  packages/sit-onyx/src/components/OnyxCheckbox/OnyxCheckbox.ct.tsx
  packages/sit-onyx/src/components/OnyxCheckbox/OnyxCheckbox.stories.ts
  packages/sit-onyx/src/components/OnyxCheckbox/OnyxCheckbox.vue
  packages/sit-onyx/src/components/OnyxCheckbox/types.ts
Labels: enhancement

#329 chore: update deprecated GitHub actions
  .github/dependabot.yml
  .github/workflows/check.yml
  .github/workflows/import-figma.yml
  .github/workflows/playwright-screenshots.yml
  .github/workflows/release.yml
Labels: dependencies

#336 docs: reorder Storybook docs page sections
  packages/sit-onyx/.storybook/docs-template.mdx
  packages/sit-onyx/.storybook/preview.ts
Labels: documentation

#64 docs: add links to documentation
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/release.yml
  README.md
  apps/docs/src/.vitepress/config.ts
  apps/docs/src/brand/team.md
  apps/docs/src/development/index.md
  apps/docs/src/development/packages/headless.md
  apps/docs/src/development/packages/storybook-utils.md
  packages/figma-utils/README.md
  packages/figma-utils/package.json
  packages/headless/README.md
  packages/headless/package.json
  packages/sit-onyx/.eslintrc.cjs
  packages/sit-onyx/README.md
  packages/sit-onyx/package.json
  packages/sit-onyx/src/i18n/index.ts
  packages/storybook-utils/README.md
  packages/storybook-utils/package.json
  packages/vitepress-theme/package.json
Labels: documentation

#367 docs(icon-library): update icon color
  apps/docs/src/.vitepress/components/IconLibraryItem.vue
Labels: documentation

#369 chore: fix deployed Storybook runtime error
  packages/storybook-utils/package.json
  pnpm-lock.yaml
Labels: bug

#394 fix: remove vulnerable dependency
  package.json
  pnpm-lock.yaml
Labels: dependencies

#408 chore: update to Storybook 8 beta
  .github/dependabot.yml
  packages/sit-onyx/.storybook/main.ts
  packages/sit-onyx/package.json
  packages/storybook-utils/package.json
  pnpm-lock.yaml
Labels: dependencies

#429 docs: fix OnyxButton code snippet when using an icon
  packages/sit-onyx/src/components/OnyxButton/OnyxButton.stories.ts
  packages/sit-onyx/src/components/OnyxIcon/OnyxIcon.stories.ts
  packages/sit-onyx/src/utils/storybook.spec.ts
  packages/sit-onyx/src/utils/storybook.ts
  packages/storybook-utils/package.json
  packages/storybook-utils/src/preview.spec.ts
  packages/storybook-utils/src/preview.ts
  packages/storybook-utils/vitest.config.ts
Labels: bug, documentation
