Repository SchwarzIT/onyx, pull requests merged in 2024-01, with the labels that each got.

#15 chore: upload eslint sarif file to GitHub
  .eslintrc.cjs
  .github/workflows/check.yml
  .gitignore
  package.json
  packages/storybook-utils/src/actions.ts
  packages/storybook-utils/src/types.ts
  pnpm-lock.yaml
Labels: enhancement

#19 docs(playwright): add link to screenshot workflow
  packages/sit-onyx/playwright.config.ts
Labels: documentation

#14 docs: add headless and storybook-utils to VitePress
  apps/docs/src/.vitepress/config.ts
  apps/docs/src/packages/headless.md
  apps/docs/src/packages/index.md
  apps/docs/src/packages/storybook-utils.md
  packages/storybook-utils/src/actions.ts
  packages/storybook-utils/src/preview.ts
Labels: documentation

#13 feat: add package `@sit-onyx/figma-utils`
  .changeset/pre.json
  .github/workflows/check.yml
  .github/workflows/import-figma.yml
  apps/docs/src/.vitepress/config.ts
  apps/docs/src/getting-started.md
  apps/docs/src/packages/figma-utils.md
  apps/docs/src/packages/headless.md
  apps/docs/src/packages/index.md
  apps/docs/src/packages/storybook-utils.md
  package.json
  packages/figma-utils/.gitignore
  packages/figma-utils/README.md
  packages/figma-utils/package.json
  packages/figma-utils/src/cli.ts
  packages/figma-utils/src/commands/import-variables.ts
  packages/figma-utils/src/index.ts
  packages/figma-utils/src/types/figma.ts
  packages/figma-utils/src/utils/fetch.ts
  packages/figma-utils/src/utils/generate.ts
  packages/figma-utils/src/utils/parse.ts
  packages/figma-utils/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#68 feat: enable form validation behavior
  .eslintrc.cjs
  apps/docs/package.json
  apps/docs/src/.env.example
  packages/sit-onyx/package.json
  packages/sit-onyx/playwright/snapshots/TestInput/default-chromium-linux.png
  packages/sit-onyx/playwright/snapshots/TestInput/default-firefox-linux.png
  packages/sit-onyx/playwright/snapshots/TestInput/default-webkit-linux.png
  packages/sit-onyx/src/components/TestInput/TestInput.spec.tsx
  packages/sit-onyx/src/components/TestInput/TestInput.stories.ts
  packages/sit-onyx/src/components/TestInput/TestInput.vue
  packages/sit-onyx/src/composables/formValidationMessage.ts
Labels: enhancement

#77 docs: add PR template
  .github/pull_request_template.md
Labels: documentation

#98 docs: fix missing external link icons
  apps/docs/package.json
  apps/docs/src/.vitepress/theme/theme.scss
  apps/docs/src/getting-started.md
  apps/docs/src/packages/figma-utils.md
  apps/docs/src/packages/headless.md
  apps/docs/src/packages/storybook-utils.md
  pnpm-lock.yaml
Labels: documentation

#97 docs: move sidebar for npm packages
  apps/docs/src/.vitepress/config.ts
  apps/docs/src/packages/index.md
Labels: documentation

#96 feat(figma-utils): add CLI option `selector`
  .changeset/sharp-years-lie.md
  .changeset/tall-keys-flow.md
  .github/workflows/import-figma.yml
  packages/figma-utils/src/commands/import-variables.ts
  packages/figma-utils/src/utils/generate.ts
Labels: enhancement

#105 chore: prevent workflows from overriding auto created PRs
  .github/workflows/import-figma.yml
  .github/workflows/playwright-screenshots.yml
Labels: bug

#75 feat(i18n): support i18n / translations
  .changeset/olive-forks-mate.md
  apps/docs/src/.vitepress/config.ts
  apps/docs/src/i18n/index.md
  apps/docs/src/i18n/languages.data.ts
  packages/sit-onyx/package.json
  packages/sit-onyx/src/components/TestInput/TestInput.spec.tsx
  packages/sit-onyx/src/components/TestInput/TestInput.stories.ts
  packages/sit-onyx/src/components/TestInput/TestInput.vue
  packages/sit-onyx/src/composables/formValidationMessage.ts
  packages/sit-onyx/src/i18n/index.spec.ts
  packages/sit-onyx/src/i18n/index.ts
  packages/sit-onyx/src/i18n/locales/de-DE.json
  packages/sit-onyx/src/i18n/locales/en-US.json
  packages/sit-onyx/src/index.ts
  packages/sit-onyx/src/types/i18n.ts
  packages/sit-onyx/src/types/utils.ts
  packages/sit-onyx/src/utils/forms.ts
  packages/sit-onyx/tsconfig.vitest.json
  packages/storybook-utils/src/preview.ts
  packages/storybook-utils/tsconfig.json
Labels: enhancement

#104 feat: add package `@sit-onyx/vitepress-theme`
  .changeset/pre.json
  apps/docs/package.json
  apps/docs/src/.vitepress/config.ts
  apps/docs/src/.vitepress/theme/index.ts
  apps/docs/src/.vitepress/theme/theme.scss
  apps/docs/src/packages/vitepress-theme.md
  packages/sit-onyx/src/styles/index.scss
  packages/vitepress-theme/README.md
  packages/vitepress-theme/package.json
  packages/vitepress-theme/src/index.scss
  packages/vitepress-theme/src/index.ts
  packages/vitepress-theme/src/mixins.scss
  packages/vitepress-theme/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#111 chore: create SECURITY.md
  SECURITY.md
Labels: documentation

#121 docs: use `@alpha` for installing packages
  apps/docs/src/getting-started.md
  apps/docs/src/packages/figma-utils.md
  apps/docs/src/packages/headless.md
  apps/docs/src/packages/storybook-utils.md
  apps/docs/src/packages/vitepress-theme.md
Labels: documentation

#130 chore(dependabot): group updates into single PR
  .github/dependabot.yml
Labels: bug

#140 chore: fix release pipeline
  .github/workflows/release.yml
Labels: bug

#142 chore: fix release workflow
  .github/workflows/release.yml
Labels: bug

#143 chore: also build storybook with `build:all` script
  package.json
Labels: bug

#144 chore: add prod manifests
  apps/docs/.cloud-foundry/manifest-prod.yml
  packages/sit-onyx/.cloud-foundry/manifest-prod.yml
Labels: bug

#84 feat: add Onyx theme for Storybook
  .changeset/modern-dingos-melt.md
  .changeset/twenty-colts-film.md
  .changeset/wild-days-admire.md
  .github/workflows/import-figma.yml
  apps/docs/src/packages/figma-utils.md
  apps/docs/src/packages/storybook-utils.md
  packages/figma-utils/.gitignore
  packages/figma-utils/README.md
  packages/figma-utils/package.json
  packages/figma-utils/src/commands/import-variables.spec.ts
  packages/figma-utils/src/commands/import-variables.ts
  packages/figma-utils/src/utils/generate.spec.ts
  packages/figma-utils/src/utils/generate.ts
  packages/sit-onyx/.storybook/docs-template.mdx
  packages/sit-onyx/.storybook/docs-template.scss
  packages/sit-onyx/.storybook/preview.ts
  packages/sit-onyx/src/styles/variables-onyx.json
  packages/storybook-utils/package.json
  packages/storybook-utils/src/assets/logo-storybook-default.svg
  packages/storybook-utils/src/assets/logo-storybook-inverse.svg
  packages/storybook-utils/src/index.css
  packages/storybook-utils/src/index.ts
  packages/storybook-utils/src/preview.ts
  packages/storybook-utils/src/theme.ts
  packages/storybook-utils/svg.d.ts
  packages/storybook-utils/tsconfig.json
  packages/vitepress-theme/src/index.scss
Labels: documentation, enhancement

#147 feat(figma-utils): sort variables when parsing
  .changeset/giant-seas-know.md
  packages/figma-utils/src/utils/parse.ts
  packages/sit-onyx/src/styles/variables-dark.css
  packages/sit-onyx/src/styles/variables-light.css
  packages/sit-onyx/src/styles/variables-onyx.css
  packages/sit-onyx/src/styles/variables-onyx.json
  packages/storybook-utils/src/theme.ts
Labels: enhancement

#156 docs: write onyx in all lowercase
  .changeset/wild-days-admire.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/import-figma.yml
  CONTRIBUTING.md
  SECURITY.md
  apps/docs/src/.vitepress/config.ts
  apps/docs/src/.vitepress/utils.ts
  apps/docs/src/getting-started.md
  apps/docs/src/i18n/index.md
  apps/docs/src/i18n/languages.data.ts
  apps/docs/src/index.md
  apps/docs/src/packages/storybook-utils.md
  apps/docs/src/packages/vitepress-theme.md
  apps/docs/src/team.md
  apps/docs/src/typography.md
  packages/headless/README.md
  packages/sit-onyx/README.md
  packages/sit-onyx/src/components/TestInput/TestInput.vue
  packages/sit-onyx/src/i18n/index.ts
  packages/storybook-utils/CHANGELOG.md
  packages/storybook-utils/src/preview.ts
  packages/storybook-utils/src/theme.ts
  packages/vitepress-theme/README.md
  packages/vitepress-theme/package.json
  packages/vitepress-theme/src/index.scss
  packages/vitepress-theme/src/mixins.scss
Labels: documentation

#154 fix(i18n): do not reset i18n when provided
  .changeset/brave-lobsters-wonder.md
  packages/sit-onyx/src/i18n/index.ts
Labels: bug

#152 fix: prevent import errors due to missing files
  .changeset/purple-years-unite.md
  .changeset/unlucky-jars-chew.md
  packages/sit-onyx/package.json
  packages/storybook-utils/package.json
  packages/storybook-utils/src/index.css
  packages/storybook-utils/src/theme.ts
  packages/vitepress-theme/package.json
  packages/vitepress-theme/src/index.scss
  pnpm-lock.yaml
Labels: bug

#164 docs: add component for showcasing color palettes
  apps/docs/src/.vitepress/components/ColorPalette.vue
  apps/docs/src/.vitepress/components/ColorPaletteValue.vue
  apps/docs/src/.vitepress/components/OnyxColorPalettes.vue
  apps/docs/src/.vitepress/config.ts
  apps/docs/src/colors.md
  packages/sit-onyx/src/styles/variables-dark.css
  packages/sit-onyx/src/styles/variables-light.css
Labels: documentation

#180 fix: prevent build error `cannot be named without a reference`
  packages/storybook-utils/src/actions.ts
  packages/storybook-utils/src/types.ts
Labels: bug

#187 docs: update navigation
  apps/docs/src/.vitepress/components/StorybookIFrame.vue
  apps/docs/src/.vitepress/config.ts
  apps/docs/src/.vitepress/env.ts
  apps/docs/src/basics/index.md
  apps/docs/src/brand/team.md
  apps/docs/src/development/[name].md
  apps/docs/src/development/[name].paths.ts
  apps/docs/src/development/colors.md
  apps/docs/src/development/getting-started.md
  apps/docs/src/development/i18n.md
  apps/docs/src/development/languages.data.ts
  apps/docs/src/development/packages/figma-utils.md
  apps/docs/src/development/packages/headless.md
  apps/docs/src/development/packages/storybook-utils.md
  apps/docs/src/development/packages/vitepress-theme.md
  apps/docs/src/development/typography.md
  apps/docs/src/index.md
  apps/docs/src/tokens/index.md
Labels: documentation

#188 docs: add missing images
  apps/docs/src/.vitepress/components/OnyxPartners.vue
Labels: bug, documentation

#172 docs: add TopicOverviewCard
  apps/docs/src/.vitepress/components/TopicOverviewCard.vue
  apps/docs/src/.vitepress/theme/index.ts
  apps/docs/src/.vitepress/theme/theme.scss
Labels: documentation

#192 docs: update facts and figures
  apps/docs/src/.vitepress/components/OnyxRoadmap.vue
  apps/docs/src/index.data.ts
Labels: documentation

#193 docs: update broken getting started link
  apps/docs/src/index.md
Labels: bug, documentation

#196 feat(docs): improve nav highlighting
  apps/docs/src/.vitepress/config.ts
Labels: bug, documentation

#174 docs: showcase spacings and border radius
  apps/docs/src/.vitepress/components/DesignToken.vue
  apps/docs/src/.vitepress/components/DesignTokenCard.vue
  apps/docs/src/.vitepress/components/OnyxBorderRadiusTokens.vue
  apps/docs/src/.vitepress/components/OnyxSpacingTokens.vue
  apps/docs/src/.vitepress/config.ts
  apps/docs/src/.vitepress/utils-browser.ts
  apps/docs/src/tokens/borders.md
  apps/docs/src/tokens/spacings.md
Labels: documentation

#204 chore: update GitHub actions
  .github/workflows/release.yml
Labels: bug

#205 feat: update default `onyx` theme
  .changeset/honest-shirts-invite.md
  apps/docs/src/.vitepress/components/ColorPalette.vue
  apps/docs/src/.vitepress/components/ColorPaletteValue.vue
  apps/docs/src/.vitepress/components/DesignToken.vue
  apps/docs/src/.vitepress/components/DesignTokenCard.vue
  apps/docs/src/.vitepress/components/OnyxBorderRadiusTokens.vue
  apps/docs/src/.vitepress/components/OnyxColorPalettes.vue
  apps/docs/src/.vitepress/components/OnyxSpacingTokens.vue
  apps/docs/src/.vitepress/components/TopicOverviewCard.vue
  apps/docs/src/.vitepress/config.ts
  apps/docs/src/basics/colors.md
  apps/docs/src/basics/units.md
  apps/docs/src/development/packages/vitepress-theme.md
  apps/docs/src/index.md
  packages/sit-onyx/src/styles/variables-dark.css
  packages/sit-onyx/src/styles/variables-light.css
  packages/sit-onyx/src/styles/variables-onyx.css
  packages/sit-onyx/src/styles/variables-onyx.json
  packages/storybook-utils/src/theme.ts
  packages/vitepress-theme/src/index.scss
  packages/vitepress-theme/src/mixins.scss
Labels: enhancement

#219 docs: remove empty pages
  apps/docs/src/.vitepress/components/OnyxRoadmap.vue
  apps/docs/src/.vitepress/config.ts
  apps/docs/src/basics/colors.md
  apps/docs/src/basics/infographics.md
  apps/docs/src/basics/units.md
  apps/docs/src/brand/changelog.md
  apps/docs/src/brand/dependencies.md
  apps/docs/src/brand/ideology.md
  apps/docs/src/brand/index.md
  apps/docs/src/brand/principles.md
  apps/docs/src/brand/roadmap.md
  apps/docs/src/resources/index.md
  apps/docs/src/tokens/index.md
Labels: documentation

#200 docs: showcase color theme
  apps/docs/src/.vitepress/components/ColorStrip.vue
  apps/docs/src/.vitepress/components/HorizontalColorStripCard.vue
  apps/docs/src/.vitepress/components/OnyxColorPalettes.vue
  apps/docs/src/.vitepress/components/OnyxColorThemeDefinitions.vue
  apps/docs/src/assets/danger.webp
  apps/docs/src/assets/info.webp
  apps/docs/src/assets/success.webp
  apps/docs/src/assets/warning.webp
  apps/docs/src/basics/colors.md
  apps/docs/src/tokens/colors.md
Labels: documentation

#211 docs: showcase typography
  apps/docs/src/.vitepress/components/ColorPalette.vue
  apps/docs/src/.vitepress/components/DesignToken.vue
  apps/docs/src/.vitepress/components/DesignTokenCard.vue
  apps/docs/src/.vitepress/components/DesignTokenHeader.vue
  apps/docs/src/.vitepress/components/OnyxBorderRadiusTokens.vue
  apps/docs/src/.vitepress/components/OnyxSpacingTokens.vue
  apps/docs/src/.vitepress/components/OnyxTypography.vue
  apps/docs/src/basics/typography.md
Labels: documentation

#232 docs(components): remove .DS_Store file from component sidebar
  apps/docs/src/.vitepress/config.ts
  apps/docs/src/.vitepress/utils.ts
  apps/docs/src/development/[name].paths.ts
Labels: documentation
